const fs=require('fs'), path=require('path'), crypto=require('crypto');
const workdir='/Users/francis7999/code/github_repos/audio-paper-digest';
const {stableSignatureSha256}=require(path.join(workdir,'scripts/manual-signature-contract.js'));
const taskRoot=path.join(workdir,'data/current/manual-v6/2026-08-29/task-runner/tasks/2608.26925');
let payload=JSON.parse(fs.readFileSync(path.join(taskRoot,'draft/revision-record-payload.json'),'utf8'));
const blocksById=new Map(payload.editorial.longformBundle.blocks.map(b=>[b.id,b]));
const b07=blocksById.get('B07');
// For each formula, set explanation to a 50-char substring that is definitely in b07 and >=40
const idx1=b07.markdown.indexOf('其中 \(w\) 是英语查询');
const exp1= idx1!==-1 ? b07.markdown.slice(idx1, idx1+70) : b07.markdown.slice(b07.markdown.indexOf('其中'), b07.markdown.indexOf('其中')+70);
const idx2=b07.markdown.indexOf('它的作用是惩罚');
const exp2= idx2!==-1 ? b07.markdown.slice(idx2, idx2+70) : 'fallback';
const idx3=b07.markdown.indexOf('语义负集合进一步聚焦');
const exp3= idx3!==-1 ? b07.markdown.slice(idx3, idx3+70) : 'fallback';
const idx4=b07.markdown.indexOf('该式是区间堆叠的对比扩展');
const exp4= idx4!==-1 ? b07.markdown.slice(idx4, idx4+70) : 'fallback';
console.log('exp1',exp1.slice(0,40),exp1.length, b07.markdown.includes(exp1));
console.log('exp2',exp2.slice(0,40),exp2.length, b07.markdown.includes(exp2));
console.log('exp3',exp3.slice(0,40),exp3.length, b07.markdown.includes(exp3));
console.log('exp4',exp4.slice(0,40),exp4.length, b07.markdown.includes(exp4));
payload.editorial.longformBundle.formulas.forEach(f=>{
  if(f.id==='FOR0001') f.explanation=exp1;
  if(f.id==='FOR0002') f.explanation=exp2;
  if(f.id==='FOR0003') f.explanation=exp3;
  if(f.id==='FOR0004') f.explanation=exp4;
  f.disposition='inline';
  f.blockId='B07';
});
const finalBytes=fs.readFileSync(path.join(taskRoot,'draft/final-article.md'));
const normalized=finalBytes.toString('utf8').normalize('NFKC').replace(/\r\n?/g,'\n').trim();
payload.editorial.longformBundle.articleSha256=crypto.createHash('sha256').update(normalized,'utf8').digest('hex');
payload.editorial.readerArticle=normalized;
const semantic=stableSignatureSha256(payload,'manual-v6-signature');
console.log('semantic',semantic);
fs.writeFileSync(path.join(taskRoot,'draft/revision-record-payload.json'), JSON.stringify(payload,null,2)+'\n');
const payloadFileSha=crypto.createHash('sha256').update(fs.readFileSync(path.join(taskRoot,'draft/revision-record-payload.json'))).digest('hex');
console.log('payloadFileSha',payloadFileSha);
const auditPath=path.join(taskRoot,'reviews/revision-independent-audit.json');
let audit=JSON.parse(fs.readFileSync(auditPath,'utf8'));
audit.articleFileSha256=crypto.createHash('sha256').update(finalBytes).digest('hex');
const mapPath=path.join(taskRoot,'draft/revision-binding-map.json');
let mapObj=JSON.parse(fs.readFileSync(mapPath,'utf8'));
mapObj.articleSha256=crypto.createHash('sha256').update(normalized,'utf8').digest('hex');
mapObj.payloadSha256=payloadFileSha;
fs.writeFileSync(mapPath, JSON.stringify(mapObj,null,2)+'\n');
const mapSha=crypto.createHash('sha256').update(fs.readFileSync(mapPath)).digest('hex');
audit.mapFileSha256=mapSha;
fs.writeFileSync(auditPath, JSON.stringify(audit,null,2)+'\n');
const auditFileSha=crypto.createHash('sha256').update(fs.readFileSync(auditPath)).digest('hex');
const auditSemantic=stableSignatureSha256(audit,'manual-v6-signature');
const outPath=path.join(taskRoot,'outputs/author-revision.json');
let output=JSON.parse(fs.readFileSync(outPath,'utf8'));
output.recordPayload.fileSha256=payloadFileSha;
output.recordPayload.semanticSha256=semantic;
output.finalArticleSha256=crypto.createHash('sha256').update(normalized,'utf8').digest('hex');
output.finalArticle.fileSha256=crypto.createHash('sha256').update(finalBytes).digest('hex');
output.independentAudit.fileSha256=auditFileSha;
output.independentAudit.semanticSha256=auditSemantic;
fs.writeFileSync(outPath, JSON.stringify(output,null,2)+'\n');
const outSemantic=stableSignatureSha256(output,'manual-v6-signature');
const receiptPath=path.join(taskRoot,'receipts/author-revision.json');
let receipt=JSON.parse(fs.readFileSync(receiptPath,'utf8'));
receipt.articleSha256=crypto.createHash('sha256').update(normalized,'utf8').digest('hex');
receipt.finalArticleSha256=crypto.createHash('sha256').update(normalized,'utf8').digest('hex');
receipt.outputSha256=outSemantic;
fs.writeFileSync(receiptPath, JSON.stringify(receipt,null,2)+'\n');
console.log('outSemantic',outSemantic);
